name: Build Workflow

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/shardeum/jenkins-test-container:latest
      # options: --user root

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Print environment info
      run: |
        echo "Checking Node version..."
        node --version
        echo "Checking npm version..."
        npm --version
        echo "Checking Rust setup..."
        rustup show
        cargo --version
        rustc --version

    - name: Install dependencies with npm ci
      run: npm ci

    - name: Build the project
      run: npm run build:dev

